# Generated by Django 5.2.3 on 2025-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tg_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('language_code', models.CharField(max_length=10)),
                ('photo_url', models.URLField(max_length=500)),
                ('is_premium', models.BooleanField()),
                ('tgWebAppPlatform', models.CharField(max_length=100)),
                ('tgWebAppVersion', models.CharField(max_length=100)),
                ('auth_date', models.DateTimeField()),
                ('chat_instance', models.CharField(max_length=200)),
                ('signature', models.CharField(max_length=255)),
                ('referral_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'User Infos',
                'managed': True,
            },
        ),
    ]
