# Generated by Django 5.2.3 on 2025-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpRequestItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('provider', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('external_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('payload', models.TextField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Top-Up Request',
                'verbose_name_plural': 'Top-Up Requests',
                'db_table': 'dashboard_topuprequestitem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('from_wallet_id', models.CharField(max_length=100)),
                ('to_wallet_id', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'dashboard_transactionitem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WalletItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'dashboard_walletitem',
                'managed': True,
            },
        ),
    ]
