# Generated by Django 5.2.3 on 2025-06-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_topuprequestitem_transactionitem_walletitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.BigIntegerField()),
                ('image_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CaseOpeningItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=100)),
                ('gift_id', models.CharField(max_length=100)),
                ('gift_type', models.CharField(max_length=100)),
                ('gift_volume', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('open_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Case Opening',
                'verbose_name_plural': 'Case Openings',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='topuprequestitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transactionitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='walletitem',
            table=None,
        ),
    ]
