# Generated by Django 5.2.3 on 2025-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_caseitem_caseopeningitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('case_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('background', models.URLField(max_length=500)),
                ('volume', models.BigIntegerField()),
                ('prob', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Gift',
                'verbose_name_plural': 'Gifts',
                'managed': True,
            },
        ),
    ]
