# Generated by Django 5.2.3 on 2025-06-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_giftitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('gift_id', models.CharField(max_length=100)),
                ('volume_fixation', models.BigIntegerField()),
                ('created_at', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='background',
            field=models.CharField(max_length=100),
        ),
    ]
