# Generated by Django 5.2.3 on 2025-06-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inventoryitem_alter_giftitem_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftitem',
            name='case_id',
        ),
        migrations.AddField(
            model_name='giftitem',
            name='case',
            field=models.ForeignKey(blank=True, db_column='case_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gifts', to='dashboard.caseitem'),
        ),
        migrations.AlterField(
            model_name='giftitem',
            name='background',
            field=models.URLField(max_length=500),
        ),
    ]
